<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__remember-me</name>
   <tag></tag>
   <elementGuidId>4b5f5b9b-e197-4b95-85ab-ba578986a674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remember-me</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember-me']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79b09f18-86c9-4fe4-abd8-f488289d20ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remember-me</value>
      <webElementGuid>b1544f3c-0965-4465-a898-065d95ee3ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remember-me</value>
      <webElementGuid>846999a0-75e6-484d-9275-3a95924c321b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3c48c091-ccca-467c-8ba7-5a4ece0dbc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-4 h-4 border-gray-300 rounded bg-gray-50 focus:outline-none active:outline-none</value>
      <webElementGuid>a7c1ccdc-c89f-46cc-b359-c692fe77fbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remember-me&quot;)</value>
      <webElementGuid>e8d46125-1f2a-41f3-b8c0-fc9cd43c324a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remember-me']</value>
      <webElementGuid>7cf7119d-cfc6-4716-bbf9-4d2e39c99f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>fe5fe570-e67c-4b56-9f1a-43c996afd3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9c7642cd-1fc3-4c56-9376-8e33d7a77edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'remember-me' and @name = 'remember-me' and @type = 'checkbox']</value>
      <webElementGuid>7613f852-1a42-45b1-b3e2-c75b4d19be93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
